// <auto-generated />
using System;
using ChatBotInpadserver.Data.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatBot_Inpad_server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatBotInpadServer.Data.Models.Admin", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Email");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$gH8gaDXr0TPHX2UK64.SZOymfKZsNQ4xGvhA4zL3Okx.j3iTyCxLW"
                        });
                });

            modelBuilder.Entity("ChatBotInpadServer.Data.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsFromUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("KnowledgeItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Telegram");

                    b.Property<string>("TextMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ChatMessages_CreatedAt");

                    b.HasIndex("IsFromUser")
                        .HasDatabaseName("IX_ChatMessages_IsFromUser");

                    b.HasIndex("KnowledgeItemId")
                        .HasDatabaseName("IX_ChatMessages_KnowledgeItemId");

                    b.HasIndex("Platform")
                        .HasDatabaseName("IX_ChatMessages_Platform");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ChatMessages_UserId");

                    b.HasIndex("Platform", "CreatedAt")
                        .HasDatabaseName("IX_ChatMessages_Platform_Time");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_ChatMessages_User_Time");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ChatBotInpadServer.Data.Models.KnowledgeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Общие вопросы");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("revit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UseCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_KnowledgeItems_Category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_KnowledgeItems_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_KnowledgeItems_UpdatedAt");

                    b.HasIndex("UseCount")
                        .HasDatabaseName("IX_KnowledgeItems_UseCount");

                    b.HasIndex("Category", "CreatedAt")
                        .HasDatabaseName("IX_KnowledgeItems_Category_CreatedAt");

                    b.HasIndex("Category", "UseCount")
                        .HasDatabaseName("IX_KnowledgeItems_Category_UseCount");

                    b.ToTable("KnowledgeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerText = "Для начала работы просто отправьте любое сообщение боту. Он ответит на ваши вопросы и поможет с настройками.",
                            Category = "Общие вопросы",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3455),
                            Tags = "начало,помощь,бот",
                            Title = "Как начать работу с ботом?",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3456),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 2,
                            AnswerText = "1. Откройте вкладку 'Architecture'\n2. Нажмите на инструмент 'Wall'\n3. Выберите тип стены\n4. Укажите точки размещения на плане",
                            Category = "Revit",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3459),
                            Tags = "revit,стена,создание",
                            Title = "Как создать новую стену в Revit?",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3459),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 3,
                            AnswerText = "🔒 Всегда проверяйте сертификаты сервера перед подключением к VPN.",
                            Category = "Безопасность",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3461),
                            Tags = "vpn,безопасность,сертификаты",
                            Title = "Безопасное подключение",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3462),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 4,
                            AnswerText = "🚀 Выбирайте сервер ближайший к вашему местоположению для лучшей скорости.",
                            Category = "Производительность",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3464),
                            Tags = "vpn,сервер,скорость,оптимизация",
                            Title = "Оптимальный сервер",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3464),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 5,
                            AnswerText = "📡 Всегда используйте VPN при подключении к публичным Wi-Fi сетям.",
                            Category = "Безопасность",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3466),
                            Tags = "vpn,безопасность,wi-fi,публичные сети",
                            Title = "Wi-Fi защита",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3466),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 6,
                            AnswerText = "📊 Если скорость низкая, попробуйте переключиться на другой сервер или протокол.",
                            Category = "Производительность",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3468),
                            Tags = "vpn,скорость,сервер,протокол,оптимизация",
                            Title = "Скорость соединения",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3469),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 7,
                            AnswerText = "📱 Мой совет это - включить акселератор.",
                            Category = "Общие советы",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3470),
                            Tags = "советы,производительность,акселератор,оптимизация",
                            Title = "Включение акселератора",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3471),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 8,
                            AnswerText = "📱 Можете проверить диск C.",
                            Category = "Общие советы",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3472),
                            Tags = "советы,диск,память,оптимизация",
                            Title = "Проверка диска",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3473),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 9,
                            AnswerText = "📱 Попробуйте закрыть вкладки браузера.",
                            Category = "Общие советы",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3475),
                            Tags = "советы,браузер,память,оптимизация",
                            Title = "Закрытие вкладок",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3475),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 10,
                            AnswerText = "📱 Незабудьте проверить рабочие наборы.",
                            Category = "Revit",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3477),
                            Tags = "revit,советы,рабочие наборы,оптимизация",
                            Title = "Проверка рабочих наборов",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3477),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 11,
                            AnswerText = "📱 Советую удалить неиспользуемые группы, виды и DWG.",
                            Category = "Revit",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3479),
                            Tags = "revit,советы,очистка,оптимизация",
                            Title = "Удаление неиспользуемых элементов",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3480),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 12,
                            AnswerText = "📱 Так же советую проверить вес файла хранилища.",
                            Category = "Revit",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3481),
                            Tags = "revit,советы,память,оптимизация",
                            Title = "Проверка веса файла",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3482),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 13,
                            AnswerText = "📱 Отключите аналитические данные.",
                            Category = "Revit",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3484),
                            Tags = "revit,советы,аналитика,оптимизация",
                            Title = "Отключение аналитики",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3484),
                            UseCount = 0
                        },
                        new
                        {
                            Id = 14,
                            AnswerText = "📱 Используйте корпоративные семейства.",
                            Category = "Revit",
                            CreatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3486),
                            Tags = "revit,советы,семейства,стандартизация",
                            Title = "Корпоративные семейства",
                            UpdatedAt = new DateTime(2026, 1, 3, 11, 43, 59, 34, DateTimeKind.Utc).AddTicks(3486),
                            UseCount = 0
                        });
                });

            modelBuilder.Entity("ChatBotInpadServer.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastActiveAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Telegram");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "PlatformId")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Platform_PlatformId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChatBotInpadServer.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("ChatBotInpadServer.Data.Models.KnowledgeItem", "KnowledgeItem")
                        .WithMany("ChatMessages")
                        .HasForeignKey("KnowledgeItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChatBotInpadServer.Data.Models.User", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KnowledgeItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatBotInpadServer.Data.Models.KnowledgeItem", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("ChatBotInpadServer.Data.Models.User", b =>
                {
                    b.Navigation("ChatMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
